require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
Rails:
  Enabled: true
Performance:
  Enabled: true

Style/StringLiterals:
  Enabled: false

# Wouldn't do in a production app, just for this interview purposes
Style/FrozenStringLiteralComment:
  Enabled: false
